eth-bridge-integration: sync with 0.13.0
namada-net/namada pull request #1012
Opened 2023-01-11 20:50 UTC by juped

The thing to look out for here is the faucet POW integration, which touches everything.

Incorporates #1002 for some easy conflict resolution, even though that's properly its own change.

2023-01-16 10:35 UTC, batconjurer requested changes

2023-01-16 10:35 UTC, batconjurer commented on apps/src/lib/node/ledger/shell/prepare_proposal.rs
> +                        has_valid_pow: queued_tx.has_valid_pow,
Doesn't this need a feature flag over the `has_valid_pow` field?

2023-01-16 10:35 UTC, batconjurer commented on shared/src/ledger/queries/router.rs
> +                // println!("Parsed {}", parsed);
What happened here?

2023-01-17 09:04 UTC, batconjurer commented on shared/src/ledger/queries/router.rs
> +                // println!("Parsed {}", parsed);
caveman debugging :hammer_and_pick:

2023-04-01 09:16 UTC, batconjurer commented
> is this still relevant?

No, we merge it a later version from main already.

2023-05-12 09:40 UTC, adrianbrink commented
> > is this still relevant?
> 
> No, we merge it a later version from main already.

Closing it then

2023-05-12 09:40 UTC, closed without merging