Shielded Inflation rewards
namada-net/namada pull request #1025
Opened 2023-01-16 08:31 UTC by mariari

A followup pr of #714 that adds the inflation rewards for the shielded pool.

The formulas follow from:

https://specs.namada.net/economics/inflation-system.html

2023-01-17 11:11 UTC, mariari commented on core/src/ledger/storage/mod.rs
> +                )
I'm not sure how this gets initialized on chain from the genesis config @brentstone @murisi would either of you know?

2023-01-17 11:22 UTC, mariari commented
It seems that currently the `e2e` tests fail, I have to investigate why still

2023-01-18 07:56 UTC, mariari commented
Currently `19` e2e tests fail:

```lisp
ifailures:
    e2e::eth_bridge_tests::everything
    e2e::ibc_tests::run_ledger_ibc
    e2e::ledger_tests::double_signing_gets_slashed ; timeout
    e2e::ledger_tests::implicit_account_reveal_pk
    e2e::ledger_tests::invalid_transactions        ; timeout
    e2e::ledger_tests::ledger_many_txs_in_a_block
    e2e::ledger_tests::ledger_txs_and_queries

    ;; Must be updated to the new rewards
    ;; "Needle: NAM: 0.2", in the temp file "NAM: 467977.4\r\n"
    e2e::ledger_tests::masp_incentives

    e2e::ledger_tests::masp_pinned_txs       ; passes on rerun (timeout?)
    e2e::ledger_tests::masp_txs_and_queries  ; passes on rerun (timeout?)
    e2e::ledger_tests::pos_bonds
    e2e::ledger_tests::pos_init_validator
    e2e::ledger_tests::pos_rewards
    e2e::ledger_tests::proposal_offline

    -- trying to connect: tcp connect error: OS error 111
    -- Figure this might be due to a timeout somewhere
    e2e::ledger_tests::proposal_submission

    e2e::ledger_tests::run_ledger_load_state_and_reset
    e2e::ledger_tests::test_genesis_validators      -- timeout
    e2e::ledger_tests::test_node_connectivity_and_consensus
    e2e::wallet_tests::wallet_encrypted_key_cmds

```

Most of them are due to timeout, rerunning two of them locally has made it pass (likely again due to timeout). With two interesting `e2e` tests failing

the first is `masp_incentives` which should be updated to the new formula, however the contrast between the expected value and what was inflated seems a bit much. It goes from `0.2 NAM` to `467977.4 NAM` if I'm reading the tmp files correctly.

The other one is `e2e::ledger_tests::proposal_submission` which gives a tcp connection error, which may be due to timeouts on epoch, however that is unconfirmed.

Overall, I think the pr should be fit to merge outside of fine tuning `masp_incentives`, with timing issues handled in further prs

2023-01-30 07:57 UTC, mariari commented
pls update wasm

2023-02-14 08:03 UTC, murisi requested changes
Thanks for the changes! Overall the code looks good. I'm mainly concerned about two and a half things:
* Is the inflation that is minted exactly equal to what is stored in `token::last_inflation(addr)`? If it is, then maybe we can make this equivalence clearer in the code... If not, we need to fix the discrepancy lest it subtly affects the PID controller.
* The conversion tree code was written under the assumption that no rewards are given for shielded NAM (and hence that no compounding takes place). This was my mistake. Since your code can potentially give rewards for locked NAM (meaning that compounding necessarily happens), the conversion tree code needs to be updated.
* Now that compounding of rewards can take place, we need to add an E2E test for this compounding behavior.

2023-06-05 01:44 UTC, mariari commented
rerolled it on brent/inflation-reward that was properly merged

2023-06-05 05:24 UTC, mariari commented
Last commit before merging v0.16.0. Note that the e2e incetives fails, but everything else works

2023-06-30 06:35 UTC, mariari commented
pls update wasms

2023-07-23 10:14 UTC, bengtlofgren commented on genesis/dev.toml
> +light_client_attack_min_slash_rate = "0.1"
Why has this been changed in this PR? Not sure I follow?

2023-07-23 10:17 UTC, bengtlofgren commented on core/src/types/token/parameters.rs
> +pub const MAX_REWARD_RATE: &str = "max_reward_rate";
I agree with @murisi here

```suggestion
pub const MAX_REWARD_RATE_KEY: &str = "max_reward_rate";
```

2023-10-20 12:10 UTC, closed without merging